#!/usr/bin/env bash

# shellcheck disable=SC2164

# Constants
declare -A LANG_CODES=(
    ['Czech']='cs_CZ'
    ['Danish']='da_DK'
    ['German']='de_DE'
    ['English']='en_US'
    ['Spanish']='es_ES'
    ['Finnish']='fi_FI'
    ['Croatian']='hr_HR'
    ['Hungarian']='hu_HU'
    ['Korean']='ko_KR'
    ['Dutch']='nl_NL'
    ['Norwegian Bokmål']='nb_NO'
    ['Polish']='pl_PL'
    ['Romanian']='ro_RO'
    ['Slovak']='sk_SK'
    ['Slovene']='sl_SI'
    ['Swedish']='sv_SE'
    ['Turkish']='tr_TR'
    ['Ukrainian']='uk_UA'
    ['Chinese']='zh_CN'
    ['French']='fr_FR'
    ['Italian']='it_IT'
    ['Japanese']='ja_JP'
    ['Portuguese']='pt_BR'
    ['Russian']='ru_RU'
)
readonly LANG_CODES

readonly VERSION=

readonly PREFIX_FONT="${WINEPREFIX}/drive_c/windows/Fonts"

readonly RED='\033[0;31m'
readonly NC='\033[0m' # No Color

function err() {
  echo -e "${RED}[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*${NC}" >&2
}

function install_fonts() {
  if [[ ! -f "${PREFIX_FONT}/Segoe UI.ttf" ]]; then
    mkdir -vp "${PREFIX_FONT}"
    cd "${PREFIX_FONT}"
    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.ttf" -O "Segoe UI.ttf"
    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/bold/latest.ttf" -O "Segoe UI Bold.ttf"
    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/light/latest.ttf" -O "Segoe UI Light.ttf"
    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semilight/latest.ttf" -O "Segoe UI Semilight.ttf"
    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/italic/latest.ttf" -O "Segoe UI Italic.ttf"
  fi
}

function is_command_installed() {
  if ! command -v "${1}" &>/dev/null
  then
    err "${1} could not be found"
    exit 1
  fi
}

function main() {
  is_command_installed '7z'
  
  if [[ -z "${VERSION}" ]]; then
    err "A version is required!"
    exit 2
  fi

  choice=$(yad --width 400 --entry --title 'Adobe Acrobat Reader DC' \
    --center \
    --width=400 \
    --button="Install:0" --button="Exit:1" \
    --text 'Select your language for installer download:' \
    --entry-text \
    "${!LANG_CODES[@]}" 2>/dev/null)
  if [[ -z "${choice}" ]]; then
    exit 0
  fi

  install_fonts

  local install_url
  install_url="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/${VERSION}/AcroRdrDC${VERSION}_${LANG_CODES["${choice}"]}.exe"
  wget -q --method HEAD "${install_url}" &>/dev/null || install_url="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/${VERSION}/AcroRdrDC${VERSION}_${LANG_CODES['English']}.exe" # fallback

  local install_exe
  install_exe=$(basename "${install_url}")
  
  # Downloads a file with progress using wget and yad
  wget "${install_url}" -O "${TMPDIR}/${install_exe}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress \
        --title="Downloading ${install_exe}" \
        --width=400 \
        --center \
        --no-buttons \
        --auto-close \
        --auto-kill \
        --on-top \
        --no-escape 2>/dev/null

  # Unpack setup files
  7z -y x "${TMPDIR}/${install_exe}" -o"${TMPDIR}/dl"
  rm -v "${TMPDIR}/${install_exe}" 2>/dev/null
  
  export INSTALL_EXE="${TMPDIR}/dl/setup.exe"
}

main
